Test3
devlup-labs/meet-scheduler pull request #76
Opened 2020-10-10 09:34 UTC by Shantanu-Bakshi

I have added the the timer as required with
1.  it shows time remaining to the next class
2.  is hidden if the time remaining is less than 24 hours
kindly accept my PR  .

2020-10-10 10:21 UTC, hirenchalodiya1 commented
@Shantanu-Bakshi, 
- first pull all commit from `master`
- change the title of PR
- mention which issues you are solving.

2020-10-10 14:01 UTC, DarshitJain04 commented
> I have added the the timer as required with
> 
> 1. it shows time remaining to the next class
> 2. is hidden if the time remaining is less than 24 hours
>    kindly accept my PR  .

@Shantanu-Bakshi also add necessary screenshots whenever you make UI changes

2020-10-10 14:09 UTC, DarshitJain04 requested changes

2020-10-10 14:09 UTC, DarshitJain04 commented on src/pages/Background/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
Do not make any changes to html/css files
Also adding links can cause Content Security Policy issues

Try looking for how to add fonts in react apps or keep the default font. Upto you

2020-10-10 14:09 UTC, DarshitJain04 commented on src/pages/Popup/components/AlarmUp.jsx
> +import './timerstyle2.css';
Don't create new css files for styling purpose
Add styles in the JSX file itself. Here is something you can use for your reference:
https://github.com/devlup-labs/meet-scheduler/blob/9e37ebe3578f29de49acde4297f4e24595fab4e9/src/pages/Popup/components/StudentForm.jsx#L15

2020-10-10 14:09 UTC, DarshitJain04 commented on src/pages/Popup/components/StudentForm.jsx
> +import './timerstyle2.css';
Same here
Don't use external css files

2020-10-10 14:09 UTC, DarshitJain04 commented on src/pages/Popup/index.html
> +  <div id="extension-app-container"></div>
Don't make any changes to any HTML/CSS files
Make any necessary changes in the JSX files itself
All the changes are bundled and added to the html files

2020-10-10 14:13 UTC, DarshitJain04 commented
@Shantanu-Bakshi all the changes that you make in the jsx files are bundled and added to the html files. You don't need to make any changes to the html files. 
Also remove the links/ imports from the html file and in case you want to use different fonts, check how to add fonts in react apps
Remove the css files you have created and add the styles in the files itself ( Check my comments, I have added a link for your reference )
In short let the existing html and css files (not the ones you added/changed) remain as it is

Also, use prettier to format your code

2020-10-10 14:17 UTC, hirenchalodiya1 requested changes
Pull latest from `devlup-labs:master` to resolve conflict in `package-lock.json`

2020-10-12 13:52 UTC, hirenchalodiya1 commented
@Shantanu-Bakshi any updates in this PR?

2020-10-13 14:05 UTC, Shantanu-Bakshi commented
for resolving issues i've made a new pull request and am therefore closing this one

2020-10-13 14:05 UTC, closed without merging